<a href="https://colab.research.google.com/github/SabrinaDJablonski/skills-introduction-to-github/blob/main/Maestr%C3%ADa_Pr%C3%A1ctica_01_introducci%C3%B3n_a_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introducción

Objetos: lista, tupla y diccionario

In [1]:
x = [3,2,9,5,1,7,4]
x

[3, 2, 9, 5, 1, 7, 4]

In [ ]:
type(x) #generalmente usamos la lista para almacenar elementos del mismo tipo, numeros, strings, etc.

list

In [2]:
a = (1, 2, 3, 4) #tuple
a

(1, 2, 3, 4)

In [3]:
type(a) #una tupla puede usarse para almacenar diferentes tipos de objetos.  son inmutables, por lo que append no funcionaria

tuple

In [4]:
#Dictionay: Dictionaries are typically created using curly braces {} with key-value pairs separated by colons : and individual pairs separated by commas ,.
b = {'Argentina': 'CABA', 'Brazil': 'San Pablo', 'Uruguay': 'Montevideo', 'Chile':'Santiago'} #siempre en el formato {key:value}, siempre tiene que haber un value asociado a key.
b

{'Argentina': 'CABA',
 'Brazil': 'San Pablo',
 'Uruguay': 'Montevideo',
 'Chile': 'Santiago'}

In [5]:
x = 1000.35
type(x)

float

In [6]:
print(x)
x = "hello world"
print(x)

1000.35
hello world


In [7]:
x = [3, 2 ,9]
y = x
print(y,x)

[3, 2, 9] [3, 2, 9]


In [8]:
x.append(4) #append se usa para una lista, no para una tupla
print(y)

[3, 2, 9, 4]


In [9]:
x=5
print(x,y)

5 [3, 2, 9, 4]


In [10]:
a = (1, 2, 3, 4)
a[0] #[] indica la ubicacion "Python uses zero-based indexing, so the first element has index 0"

1

In [11]:
a.index(2)

1

In [12]:
a[-4]

1

In [15]:
a[1:10] #slicing

(2, 3, 4)

##Ejercicios

In [16]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
planets

['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']

In [21]:
cercano=planets[0]
lejano=planets[7]
primeros_3=planets[0:3]
ultimos_3=planets[-3:]
planets.append('Tatooine')
cercano, lejano, primeros_3, ultimos_3, planets

('Mercury',
 'Neptune',
 ['Mercury', 'Venus', 'Earth'],
 ['Saturn', 'Uranus', 'Neptune'],
 ['Mercury',
  'Venus',
  'Earth',
  'Mars',
  'Jupiter',
  'Saturn',
  'Uranus',
  'Neptune',
  'Tatooine'])

Cuál es el planeta más cercano al sol?

Cuál es el planeta más lejano del sol?

Cuáles son los 3 primeros planetas?

Cuáles son los últimos 3 planetas?

Cómo agrego el planeta Tatooine al final de la lista?

In [ ]:
planets[0]

'Mercury'

In [ ]:
planets[-1]

'Neptune'

In [ ]:
planets[:3]

['Mercury', 'Venus', 'Earth']

In [ ]:
planets[-3:]

['Saturn', 'Uranus', 'Neptune']

In [ ]:
planets.append('Tatooine')
planets

['Mercury',
 'Venus',
 'Earth',
 'Mars',
 'Jupiter',
 'Saturn',
 'Uranus',
 'Neptune',
 'Tatooine']

In [22]:
#quiero reemplazar un planeta que se llama "Tatooine" en el 3er lugar
planets[2]='Tatooine'
planets

['Mercury',
 'Venus',
 'Tatooine',
 'Mars',
 'Jupiter',
 'Saturn',
 'Uranus',
 'Neptune',
 'Tatooine']

In [23]:
del planets[2] #eliminar 'Tatooine' para que no aparezca 2 veces.
planets
planets.insert(2,'Tatooine')
planets

['Mercury',
 'Venus',
 'Tatooine',
 'Mars',
 'Jupiter',
 'Saturn',
 'Uranus',
 'Neptune',
 'Tatooine']

In [24]:
len(planets)

9

# Operadores

In [25]:
x = 15 + 1.3

print(x)

16.3


In [26]:
x = 40
y = 12

add = x + y
sub = x - y
pro = x * y
div = x / y

print(add)
print(sub)
print(pro)
print(div)

52
28
480
3.3333333333333335


In [27]:
a = 13.2
b = 12.57

c = a + int(b) #Suma solo la parte entera de b
print(c)

25.2


In [28]:
a = 13
b = 5

c = a / b
print(c)

2.6


In [29]:
numbers = [2, 4, 6, 8]
x = [12, 14, 18]
numbers + x

[2, 4, 6, 8, 12, 14, 18]

In [ ]:
numbers.reverse()
numbers

[8, 6, 4, 2]

In [ ]:
numbers.sort() #por default es ascendente
numbers

[2, 4, 6, 8]

In [ ]:
numbers.sort(reverse=True) #ordenar en forma descendente
numbers

[8, 6, 4, 2]

For

In [ ]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
for planet in planets:
    print(planet, end=' ') # print all on same line, end=' ' means there is a space between each planet

Mercury Venus Earth Mars Jupiter Saturn Uranus Neptune 

In [ ]:
a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
for number in a:
    if number < 55:
        print(number, end=' ')

1 1 2 3 5 8 13 21 34 

##Ejercicio: cómo se interpreta el siguiente código?

In [ ]:
import random
list_1=[]
for n in range(7):
    n =random.randint(1,101)
    list_1.append(n)
print(list_1)

[8, 23, 44, 55, 31, 90, 11]


##Crear Dataframe con Pandas

In [ ]:
# import pandas as pd
import pandas as pd

# List1  Es una lista de listas
list1 = [['Amarillo', 25], ['Rojo', 30],
       ['Negro', 26], ['Azul', 22]]

# creating df object with columns specified
df = pd.DataFrame(list1, columns =['color', 'número'])
print(df)

      color  número
0  Amarillo      25
1      Rojo      30
2     Negro      26
3      Azul      22


In [ ]:
# Two-dimensional list
data = [['Martin', 28, 'Analyst'],
        ['Micaela', 35, 'Manager'],
        ['Mateo', 29, 'Developer']]

# Column names
columns = ['Name', 'Age', 'Occupation']

# Creating DataFrame using pd.DataFrame.from_records()
df = pd.DataFrame.from_records(data, columns=columns)

# Displaying the DataFrame
print(df)

      Name  Age Occupation
0   Martin   28    Analyst
1  Micaela   35    Manager
2    Mateo   29  Developer


In [ ]:
# Creating a DataFrame with different data types from a list of lists
data = [['Gabriel', 28, 'Engineer'],
        ['Gina', 25, 'Data Scientist'],
        ['Gonzalo', '32', 'Manager']]  # Age represented as a string

columns = ['Name', 'Age', 'Occupation']

df = pd.DataFrame(data, columns=columns)
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')  # Convert 'Age' column to numeric, handling errors
print(df)

      Name  Age      Occupation
0  Gabriel   28        Engineer
1     Gina   25  Data Scientist
2  Gonzalo   32         Manager


In [ ]:
# initialize list of lists
data = [[1, 5, 10], [2, 6, 9], [3, 7, 8]]

# Create the pandas DataFrame
df = pd.DataFrame(data)

# specifying column names
df.columns = ['Col_1', 'Col_2', 'Col_3']

# print dataframe.
print(df, "\n") #cambio de fila

# transpose of dataframe
df = df.transpose()
print("Transpose of above dataframe is-\n", df)

   Col_1  Col_2  Col_3
0      1      5     10
1      2      6      9
2      3      7      8 

Transpose of above dataframe is-
         0  1  2
Col_1   1  2  3
Col_2   5  6  7
Col_3  10  9  8


In [ ]:
# data in the form of list of tuples
data = [('Peter', 18, 7),
        ('Riff', 15, 6),
        ('John', 17, 8),
        ('Michel', 18, 7),
        ('Sheli', 17, 5) ]

# create DataFrame using data
df = pd.DataFrame(data, columns =['Name', 'Age', 'Score'])

print(df)

     Name  Age  Score
0   Peter   18      7
1    Riff   15      6
2    John   17      8
3  Michel   18      7
4   Sheli   17      5


In [ ]:
# Initialise data to lists.
data = [{'Alice': 'book', 'in': 'for', 'Wonderland': 'children'},
        {'Alice':10, 'in': 20, 'Wonderland': 30}]

df = pd.DataFrame.from_records(data,index=['1', '2'])
print(df)

  Alice   in Wonderland
1  book  for   children
2    10   20         30


##Ejercicio en clase
###Armar un dataframe de 5 filas con paises y su capital correspondiente

In [ ]:
# import pandas as pd
import pandas as pd

# List1  Es una lista de listas
lst = [['Argentina', 'CABA'], ['Francia', 'Paris'],
       ['China', 'Beijing'], ['Canada', 'Otawa'],['Australia','Canberra']]

# creating df object with columns specified
df = pd.DataFrame(lst, columns =['Pais', 'Capital'])
print(df)

        Pais   Capital
0  Argentina      CABA
1    Francia     Paris
2      China   Beijing
3     Canada     Otawa
4  Australia  Canberra


##Numpy

In [ ]:
import numpy as np

empty_array_2d = np.empty((3, 4)) #crear vectores con 0
print(empty_array_2d)

[[5.22504260e-315 0.00000000e+000 2.10077583e-312 6.79038654e-313]
 [2.22809558e-312 2.14321575e-312 2.35541533e-312 6.79038654e-313]
 [2.22809558e-312 2.14321575e-312 2.46151512e-312 2.41907520e-312]]


In [ ]:
full_array_2d = np.full((3, 4), 5) #crear vectores con 5
print(full_array_2d)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
import numpy as np

# declare matrix with np
M = np.array([[2, 3], [4, 5]])

# using array.flatten() method
flat_M = M.flatten()
print(flat_M)

[2 3 4 5]


In [ ]:
# Create a numpy array
arr = np.array([10, 20, 30, 40, 50])
# Print the array
print(arr)

[10 20 30 40 50]


In [ ]:
print(arr.dtype)

int64


In [ ]:
# change the dtype to 'float64'
arr = arr.astype('float64')
print(arr)

# print the data type
print(arr.dtype)

[10. 20. 30. 40. 50.]
float64


In [ ]:
import pandas as pd
import numpy as np

# Creating a DataFrame with missing values from a list of lists
data = [['Gabriel', 28, 'Engineer'],
        ['Gina', None, 'Data Scientist'],
        ['Gonzalo', 32, None]]

columns = ['Name', 'Age', 'Occupation']

df = pd.DataFrame(data, columns=columns)
df = df.replace({None: np.nan})  # Replacing None with NaN for missing values
print(df)

      Name   Age      Occupation
0  Gabriel  28.0        Engineer
1     Gina   NaN  Data Scientist
2  Gonzalo  32.0             NaN
